version: '3.8'

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app/data
      - ./logs:/app/logs
    expose:
      - 8000
    command: >
      sh -c "python init_sqlite_amvera.py &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn mom_baby_bot.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120"

  bot:
    build: .
    restart: always
    depends_on:
      - web
    env_file:
      - ./.env
    volumes:
      - sqlite_data:/app/data
      - ./logs:/app/logs
    command: python manage.py run_bot

  nginx:
    image: nginx:1.21-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx

volumes:
  redis_data:
  static_volume:
  media_volume:
  sqlite_data: