# Generated by Django 4.2.7 on 2025-07-30 10:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('left_breast_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Продолжительность кормления левой грудью')),
                ('right_breast_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Продолжительность кормления правой грудью')),
                ('left_timer_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало таймера левой груди')),
                ('right_timer_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало таймера правой груди')),
                ('left_timer_active', models.BooleanField(default=False, verbose_name='Активен ли таймер левой груди')),
                ('right_timer_active', models.BooleanField(default=False, verbose_name='Активен ли таймер правой груди')),
                ('feeding_type', models.CharField(choices=[('breast', 'Грудное вскармливание'), ('bottle', 'Кормление из бутылочки'), ('mixed', 'Смешанное кормление')], default='breast', max_length=10, verbose_name='Тип кормления')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Количество (мл)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('last_active_breast', models.CharField(blank=True, choices=[('left', 'Левая грудь'), ('right', 'Правая грудь'), ('both', 'Обе груди')], max_length=5, null=True, verbose_name='Последняя активная грудь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия кормления',
                'verbose_name_plural': 'Сессии кормления',
                'ordering': ['-start_time'],
            },
        ),
    ]
