# Generated by Django 4.2.7 on 2025-07-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_add_health_tracking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('pregnancy_info', 'Информация о беременности'), ('nutrition_advice', 'Советы по питанию'), ('child_development', 'Развитие ребенка'), ('health_tracking', 'Отслеживание показателей здоровья'), ('kick_counter', 'Счетчик шевелений'), ('feeding_tracker', 'Отслеживание кормления'), ('sleep_tracker', 'Отслеживание сна'), ('vaccine_calendar', 'Календарь прививок'), ('general_recommendations', 'Общие рекомендации')], max_length=50, verbose_name='Функция/раздел')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подтверждения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_acknowledgments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение дисклеймера',
                'verbose_name_plural': 'Подтверждения дисклеймера',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
