# Generated by Django 4.2.7 on 2025-07-31 07:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_personalizedcontent_userprofile_usercontentview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('tip_type', models.CharField(choices=[('tip', 'Совет'), ('fact', 'Факт'), ('milestone', 'Веха развития'), ('reminder', 'Напоминание'), ('warning', 'Предупреждение')], default='tip', max_length=20, verbose_name='Тип совета')),
                ('pregnancy_week_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(42)], verbose_name='Минимальная неделя беременности')),
                ('pregnancy_week_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(42)], verbose_name='Максимальная неделя беременности')),
                ('baby_age_min_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный возраст ребенка (дни)')),
                ('baby_age_max_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальный возраст ребенка (дни)')),
                ('audience', models.CharField(choices=[('pregnant', 'Беременные'), ('new_mom', 'Молодые мамы'), ('experienced_mom', 'Опытные мамы'), ('all', 'Все пользователи')], default='all', max_length=20, verbose_name='Целевая аудитория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.IntegerField(default=1, help_text='Чем выше число, тем выше приоритет', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Приоритет (1-10)')),
                ('show_date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала показа')),
                ('show_date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Ежедневный совет',
                'verbose_name_plural': 'Ежедневные советы',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyTipView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('interaction_type', models.CharField(choices=[('viewed', 'Просмотрен'), ('liked', 'Понравился'), ('dismissed', 'Отклонен'), ('shared', 'Поделился')], default='viewed', max_length=20, verbose_name='Тип взаимодействия')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='webapp.dailytip', verbose_name='Совет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tip_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр ежедневного совета',
                'verbose_name_plural': 'Просмотры ежедневных советов',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
