# Generated by Django 4.2.7 on 2025-07-31 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_dailytip_userdailytipview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Описание достижения')),
                ('achievement_type', models.CharField(choices=[('pregnancy_milestone', 'Веха беременности'), ('baby_milestone', 'Веха развития ребенка'), ('feeding_milestone', 'Достижение в кормлении'), ('health_milestone', 'Достижение в здоровье'), ('app_usage', 'Использование приложения'), ('data_tracking', 'Отслеживание данных'), ('special_event', 'Особое событие')], max_length=30, verbose_name='Тип достижения')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкое'), ('medium', 'Среднее'), ('hard', 'Сложное'), ('legendary', 'Легендарное')], default='medium', max_length=15, verbose_name='Сложность')),
                ('icon', models.CharField(default='🏆', help_text='Эмодзи или название иконки для отображения достижения', max_length=50, verbose_name='Иконка')),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Очки за достижение')),
                ('condition_type', models.CharField(choices=[('pregnancy_week', 'Достижение определенной недели беременности'), ('baby_age_days', 'Возраст ребенка в днях'), ('feeding_sessions', 'Количество сессий кормления'), ('weight_records', 'Количество записей веса'), ('blood_pressure_records', 'Количество записей давления'), ('app_usage_days', 'Дни использования приложения'), ('consecutive_days', 'Последовательные дни использования'), ('data_completeness', 'Полнота заполнения данных'), ('special_date', 'Особая дата')], max_length=50, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(blank=True, help_text='Числовое значение для условия (например, неделя беременности, количество записей)', null=True, verbose_name='Значение условия')),
                ('condition_data', models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры для сложных условий', verbose_name='Дополнительные данные условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_hidden', models.BooleanField(default=False, help_text='Скрытые достижения не показываются пользователю до получения', verbose_name='Скрытое')),
                ('show_progress', models.BooleanField(default=True, help_text='Показывать ли прогресс выполнения условия', verbose_name='Показывать прогресс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['difficulty', 'points', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AchievementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('achievement_earned', 'Достижение получено'), ('milestone_reached', 'Веха достигнута'), ('progress_update', 'Обновление прогресса'), ('encouragement', 'Поощрение')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка отправки')], default='pending', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webapp.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о достижении',
                'verbose_name_plural': 'Уведомления о достижениях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('progress_data', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация о том, как было получено достижение', verbose_name='Данные прогресса')),
                ('is_viewed', models.BooleanField(default=False, help_text='Видел ли пользователь уведомление о получении достижения', verbose_name='Просмотрено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='webapp.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
