# Generated by Django 4.2.7 on 2025-07-31 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_achievement_achievementnotification_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Дата, рассчитанная врачом на основе УЗИ или последней менструации', verbose_name='Предполагаемая дата родов (ПДР)')),
                ('last_menstrual_period', models.DateField(blank=True, help_text='Используется для расчета срока беременности', null=True, verbose_name='Дата последней менструации')),
                ('conception_date', models.DateField(blank=True, help_text='Если известна точная дата зачатия', null=True, verbose_name='Дата зачатия')),
                ('is_active', models.BooleanField(default=True, help_text='False если беременность завершилась', verbose_name='Активная беременность')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о беременности', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о беременности',
                'verbose_name_plural': 'Информация о беременности',
                'ordering': ['-created_at'],
            },
        ),
    ]
