# Generated by Django 4.2.7 on 2025-07-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_add_pregnancy_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
