# Generated by Django 4.2.7 on 2025-07-31 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_change_pregnancy_info_to_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyWeekNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(42)], verbose_name='Номер недели беременности')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка отправки')], default='pending', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('pregnancy_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_notifications', to='webapp.pregnancyinfo', verbose_name='Информация о беременности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_week_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о неделе беременности',
                'verbose_name_plural': 'Уведомления о неделях беременности',
                'ordering': ['-week_number', '-created_at'],
                'unique_together': {('user', 'pregnancy_info', 'week_number')},
            },
        ),
    ]
