# Generated by Django 4.2.7 on 2025-07-31 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_pregnancyweeknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetalDevelopmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(42)], verbose_name='Номер недели беременности')),
                ('title', models.CharField(help_text='Например: "4-я неделя беременности"', max_length=200, verbose_name='Заголовок недели')),
                ('fetal_size_description', models.CharField(blank=True, help_text='Например: "Размером с маковое зернышко"', max_length=200, verbose_name='Описание размера плода')),
                ('fetal_length_mm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина плода (мм)')),
                ('fetal_weight_g', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес плода (г)')),
                ('organ_development', models.TextField(blank=True, help_text='Описание того, какие органы и системы развиваются на этой неделе', verbose_name='Развитие органов и систем')),
                ('maternal_changes', models.TextField(blank=True, help_text='Описание изменений, которые происходят в организме матери', verbose_name='Изменения в организме мамы')),
                ('common_symptoms', models.TextField(blank=True, help_text='Список симптомов, которые могут возникнуть на этой неделе', verbose_name='Частые симптомы')),
                ('recommendations', models.TextField(blank=True, help_text='Рекомендации по питанию, образу жизни, медицинским обследованиям', verbose_name='Рекомендации')),
                ('dos_and_donts', models.TextField(blank=True, help_text='Список рекомендаций о том, что следует делать и чего избегать', verbose_name='Что можно и нельзя делать')),
                ('medical_checkups', models.TextField(blank=True, help_text='Рекомендуемые медицинские обследования на этой неделе', verbose_name='Медицинские обследования')),
                ('interesting_facts', models.TextField(blank=True, help_text='Интересные факты о развитии плода на этой неделе', verbose_name='Интересные факты')),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to='fetal_development/', verbose_name='Иллюстрация развития плода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Информация о развитии плода',
                'verbose_name_plural': 'Информация о развитии плода',
                'ordering': ['week_number'],
            },
        ),
    ]
