name: Проверка качества кода

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Получение кода
      uses: actions/checkout@v4
    
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Кэширование зависимостей pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-quality-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-quality-
    
    - name: Установка инструментов качества кода
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety
        pip install -r requirements.txt
    
    - name: Проверка форматирования с Black
      run: |
        echo "🔍 Проверка форматирования кода..."
        black --check --diff --color .
    
    - name: Проверка сортировки импортов с isort
      run: |
        echo "📦 Проверка сортировки импортов..."
        isort --check-only --diff --color .
    
    - name: Проверка стиля кода с flake8
      run: |
        echo "📏 Проверка стиля кода..."
        flake8 . --statistics
    
    - name: Проверка типов с mypy
      run: |
        echo "🔍 Проверка типов..."
        mypy --ignore-missing-imports --show-error-codes .
      continue-on-error: true
    
    - name: Проверка безопасности с bandit
      run: |
        echo "🔒 Проверка безопасности кода..."
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . -f txt || true
    
    - name: Проверка уязвимостей в зависимостях
      run: |
        echo "🛡️ Проверка уязвимостей в зависимостях..."
        safety check --json || true
    
    - name: Загрузка отчетов
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: code-quality-reports
        path: |
          bandit-report.json
        retention-days: 30
    
    - name: Комментарий в PR с результатами
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let comment = '## 📊 Результаты проверки качества кода\n\n';
          
          // Добавляем информацию о проверках
          comment += '✅ Все проверки качества кода завершены.\n';
          comment += 'Подробные результаты доступны в логах GitHub Actions.\n\n';
          comment += '### Выполненные проверки:\n';
          comment += '- 🎨 Форматирование кода (Black)\n';
          comment += '- 📦 Сортировка импортов (isort)\n';
          comment += '- 📏 Стиль кода (flake8)\n';
          comment += '- 🔍 Проверка типов (mypy)\n';
          comment += '- 🔒 Безопасность кода (bandit)\n';
          comment += '- 🛡️ Уязвимости зависимостей (safety)\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
      continue-on-error: true